apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: final
data:
  BG_IMAGE_URL: s3://rupesh-project-bucket/dogs.png
  DBHOST: 172.17.0.2
  GROUP_NAME: InfraNinjas
  GROUP_SLOGAN: ChatGPT Pro Max
