apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: final
type: Opaque
stringData:
  # AWS credentials (used by your app at runtime)
  AWS_ACCESS_KEY_ID: <AWS_ACCESS_KEY_ID>
  AWS_SECRET_ACCESS_KEY: <AWS_SECRET_ACCESS_KEY>
  AWS_SESSION_TOKEN: <AWS_SESSION_TOKEN>
  
  # MySQL credentials (to match what your mysql StatefulSet is using)
  DBUSER: <DBUSER>
  DBPWD: <DBPWD>
  # Note: The DBHOST is set in the deployment.yaml file, not here.
