---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rv-eks-cluster
  region: "us-east-1"
  version: "1.31"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<CUSTOM_ROLE_NAME>
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::<AWS_ACCOUNT_ID>:role/<CUSTOM_ROLE_NAME>
